---
sudo: true
language: python
python: "2.7"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-apt

install:
  - pip install ansible

before_script:
  - echo localhost > test/inventory
  - ansible-galaxy install --role-file requirements.yml
  - ./test/gen-duplicity-keys.sh
  - ./test/gen-test-cert.sh

script:
  - ansible-playbook -i test/inventory test.yml --syntax-check
  - ansible-playbook -i test/inventory test.yml --connection=local --sudo
