---
- name: Create gpg home
  file: name="/var/gpg" state=directory owner=sandstorm mode=0700

- name: install dependencies
  apt: name={{item}} state=present
  with_items:
    - gnupg
    - duplicity

- name: import backup encryption key
  command: sudo -u sandstorm gpg --homedir /var/gpg --import /var/gpg/backup-encryption-public.key

- name: import signing key
  command: sudo -u sandstorm gpg --homedir /var/gpg --import /var/gpg/backup-signing-private.key
