---
- name: Create gpg home
  file: name="/var/gpg" state=directory owner=root mode=0700

- name: Create duplicity archive directory
  file: name="/var/duplicity-archive" state=directory owner=root mode=0700

- name: Install dependencies
  apt: name={{item}} state=present
  with_items:
    - gnupg
    - duplicity

- name: Check for backup encryption key
  command: gpg --homedir /var/gpg --list-keys {{backup_encryption_key_id}}
  ignore_errors: True
  become_user: root
  register: backup_encryption_key_exists

- name: Import backup encryption key
  command: gpg --homedir /var/gpg --import /var/gpg/backup-encryption-public.key
  become_user: root
  when: not backup_encryption_key_exists.rc == 0

- name: Check for backup signing key
  command: gpg --homedir /var/gpg --list-keys {{backup_signing_key_id}}
  ignore_errors: True
  become_user: root
  register: backup_signing_key_exists

- name: Import signing key
  command: gpg --homedir /var/gpg --import /var/gpg/backup-signing-private.key
  become_user: root
  when: not backup_signing_key_exists.rc == 0

- name: add backup script
  template: src=backup-sandstorm.j2 dest=/usr/local/bin/backup-sandstorm mode=a+x

- name: add crontab entry for duplicity
  cron:
    name="backup sandstorm"
    hour=23
    user="root"
    job="/usr/local/bin/backup-sandstorm"
    cron_file=backup-sandstorm
