---
- name: Ensure we have exim4 so sandstorm can send login emails
  apt: name=exim4

- name: Configure exim4 to allow sending to internet and bind to 127.0.0.1
  template:
    src: update-exim4.conf.conf.j2
    dest: /etc/exim4/update-exim4.conf.conf
    mode: 0644

- name: Update exim4 config
  command: update-exim4.conf

- name: Ensure exim4 is started and enabled to start at boot.
  service: name=exim4 state=started enabled=yes
